name: Run in managed venv
inputs:
  run:
    required: true
    description: The command to run inside the virtual environment.
    type: string
  python-version:
    default: "3.11"
    required: false
    type: string
  package-manager:
    default: pipenv
    description: Package manager to use (pip, pipenv or poetry)
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - if: inputs.package-manager == 'pip'
      run: python -m ${{ run }}
    - if: inputs.package-manager == 'pipenv'
      run: pipenv run ${{ run }}
    - if: inputs.package-manager == 'poetry'
      run: poetry run ${{ run }}
