name: Get package version
inputs:
  package-manager:
    default: pipenv
    description: Package manager to use (pip, pipenv or poetry)
    required: false
    type: string
  package:
    description: "The package name to get the version for."
    required: true
    type: string
  group:
    default: "default"
    description: "The package group which the dependency can be found in"
    required: false
    type: string
  python-version:
    default: "3.11"
    required: false
    type: string
  requirements-files:
      default: requirements.txt
      description: "Space-separated list of requirements files if using pip"
      required: false
      type: string
outputs:
  version:
    description: "The package version, if found"
    value: ${{ steps.get_version.outputs.version }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      if: inputs.package-manager == 'poetry'
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install poetry
      if: inputs.package-manager == 'poetry'
      run: pipx install poetry
      shell: bash
    - id: get_version
      run: echo "version=`$GITHUB_ACTION_PATH/get_version.sh`" >> $GITHUB_OUTPUT
      env:
        INPUT_PACKAGE: ${{ inputs.package }}
        INPUT_GROUP: ${{ inputs.group }}
        INPUT_PACKAGE_MANAGER: ${{ inputs.package-manager }}
        INPUT_REQUIREMENTS_FILES: ${{ inputs.requirements-files }}
      shell: bash
