name: Run command in a managed venv
inputs:
  command:
    required: true
    description: The command to run inside the virtual environment.
    type: string
  module:
    required: false
    description: The module to run inside the virtual environment (uv-only).
    type: string
  package-manager:
    default: pipenv
    description: Package manager to use (pip, pipenv, poetry or uv)
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - if: inputs.package-manager == 'pip'
      run: python -m ${{ inputs.command }}
      shell: bash
    - if: inputs.package-manager == 'pipenv'
      run: pipenv run ${{ inputs.command }}
      shell: bash
    - if: inputs.package-manager == 'poetry'
      run: poetry run ${{ inputs.command }}
      shell: bash
    - if: inputs.package-manager == 'uv'
      run: uv run -- python -m ${{ inputs.module }}
      shell: bash
