name: Install pip dependencies
inputs:
  python-version:
    default: "3.11"
    required: false
    type: string
  requirements-files:
    default: requirements.txt
    description: Space-separated list of requirements files if using pip
    required: false
    type: string
  use-private-repo:
    default: false
    description: Use the ZUoS private GCloud Artifact Registry (required GCloud authentication)
    required: false
    type: boolean

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        cache: "pip"
        python-version: "3.11"
    - name: Prepare Google Artifact Registry keyring
      if: inputs.use-private-repo == 'true'
      # Install dependencies for accessing our private packages repo (keyring for authenticating to GCP Artifact Registry).
      run: pip install -r requirements-gcloud-keyring.txt
      shell: bash
    - name: Install dependencies
      run: python -m pip install -r ${{ inputs.requirements-files }}
      shell: bash
