name: Install poetry dependencies
inputs:
  python-version:
    default: "3.12"
    required: false
    type: string
  with_root:
    default: false
    required: false
    type: boolean

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        cache: "poetry"
        python-version: ${{ inputs.python-version }}
    - name: Install poetry
      run: pipx install poetry
      shell: bash
    - name: Prepare Google Artifact Registry keyring
      if: env.GOOGLE_APPLICATION_CREDENTIALS
      # Install dependencies for accessing our private packages repo (keyring for authenticating to GCP Artifact Registry).
      run: poetry self add "keyrings-google-artifactregistry-auth@latest"
      shell: bash
    - name: Install poetry dependencies
      if: inputs.with_root == 'false'
      run: poetry install --all-extras --no-interaction --no-root
      shell: bash
    - name: Install poetry dependencies with root
      if: inputs.with_root == 'true'
      run: poetry install --all-extras --no-interaction
      shell: bash
