name: Install poetry dependencies
inputs:
  python-version:
    default: "3.11"
    required: false
    type: string
  with_root:
    default: false
    required: false
    type: boolean

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - uses: abatilo/actions-poetry@v3
    - uses: actions/cache@v4
      name: Setup cache
      with:
        path: ./.venv
        key: poetry-lock-${{ hashFiles('poetry.lock') }}
        # We always set "in-project" in poetry.toml to ensure a local .venv, as
        # we require that for pyright and other pre-commit hooks.
    - name: Prepare Google Artifact Registry keyring
      if: env.GOOGLE_APPLICATION_CREDENTIALS
      # Install dependencies for accessing our private packages repo (keyring for authenticating to GCP Artifact Registry).
      run: poetry self add "keyrings-google-artifactregistry-auth@latest"
      shell: bash
    - name: Install poetry dependencies
      if: inputs.with_root == 'false'
      run: poetry install --all-extras --no-interaction --no-root
      shell: bash
    - name: Install poetry dependencies with root
      if: inputs.with_root == 'true'
      run: poetry install --all-extras --no-interaction
      shell: bash
