name: Install system dependencies
inputs:
  system-dependencies:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: ${{ inputs.system-dependencies }}
