name: Install dependencies
inputs:
  package-manager:
    default: uv
    description: Package manager to use (uv or poetry)
    required: false
    type: string
  project-directory:
    required: false
    type: string
    default: .

runs:
  using: "composite"
  steps:
    - name: Compare Poetry versions
      if: inputs.package-manager == 'poetry'
      uses: scene-connect/actions/compare-versions/poetry@ZUS-1489_ci_version_checks
      with:
        project-directory: ${{ inputs.project-directory }}
    - name: Compare uv versions
      if: inputs.package-manager == 'uv'
      uses: scene-connect/actions/compare-versions/uv@ZUS-1489_ci_version_checks
      with:
        project-directory: ${{ inputs.project-directory }}
