name: Install dependencies
inputs:
  python-version:
    default: "3.11"
    required: false
    type: string
  package-manager:
    default: pipenv
    description: Package manager to use (pip, pipenv or poetry)
    required: false
    type: string
  requirements-files:
    default: requirements.txt
    description: Space-separated list of requirements files if using pip
    required: false
    type: string
  with_root:
    default: false
    description: should the root package be installed (poetry only). Required for src layout and pytest
    required: false
    type: boolean
  system-dependencies:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Install system dependencies
      if: inputs.system-dependencies
      uses: ./install-system-dependencies
      with:
        system-dependencies: ${{ inputs.system-dependencies }}
    - name: Install pip requirements
      if: inputs.package-manager == 'pip'
      uses: ./python-package-manager/install-dependencies/pip
      with:
        python-version: ${{ inputs.python-version }}
        requirements-files: ${{ inputs.requirements-files }}
    - name: Install pipenv requirements
      if: inputs.package-manager == 'pipenv'
      uses: ./python-package-manager/install-dependencies/pipenv
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install poetry requirements
      if: inputs.package-manager == 'poetry'
      uses: ./python-package-manager/install-dependencies/poetry
      with:
        with_root: ${{ inputs.with_root }}
        python-version: ${{ inputs.python-version }}
