name: Install system dependencies
inputs:
  system-dependencies:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - if: ${{ inputs.system-dependencies }}
      run: |
        sudo apt-get -y update
        sudo apt-get -y install --no-install-recommends ${{ inputs.system-dependencies }}
      shell: bash
