name: Install system dependencies
inputs:
  system-dependencies:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - if: ${{ inputs.system-dependencies }}
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: ${{ inputs.system-dependencies }}
