name: Dependabot auto-merge
on: pull_request_target

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/dependabot-auto-merge.yml
