name: Docker build and publish and optional kubernetes deploy
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-repo-name:
        required: false
        type: string
        default: "ops"
      deployment-name:
        required: false
        type: string
      cluster-name:
        required: false
        type: string
      cluster-zone:
        required: false
        type: string
      gcp-project:
        description: "Google Cloud Platform project id."
        type: string
        required: true
      docker-push:
        description: "Whether or not to push the docker image."
        type: boolean
        required: false
        default: false
    secrets:
      GOOGLE_AUTHENTICATION_CREDENTIALS_JSON:
        description: "Google Cloud Platform service-agent JSON credentials for accessing our Artifact Repository and installing private packages."
        required: false
env:
  full_image_uri: europe-north1-docker.pkg.dev/${{ inputs.gcp-project }}/${{ inputs.image-repo-name }}/${{ inputs.image-name }}
jobs:
  docker_build:
    runs-on: ubuntu-22.04
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Store google auth secret file
        run: echo '${{ secrets.GOOGLE_AUTHENTICATION_CREDENTIALS_JSON }}' |tee /tmp/google_auth_credentials.json
      - name: Login to Google Artifact Registry docker repo
        uses: docker/login-action@v3
        with:
          registry: europe-north1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_AUTHENTICATION_CREDENTIALS_JSON }}
      - name: Build builder image
        uses: docker/build-push-action@v6
        with:
          build-args: BUILDKIT_INLINE_CACHE=1
          cache-from: ${{ env.full_image_uri }}-builder:latest
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: ${{ inputs.docker-push }}
          tags: |
            ${{ env.full_image_uri }}-builder:latest
            ${{ env.full_image_uri }}-builder:${{ github.sha }}
          target: builder
          secret-files: |
            "google_application_credentials.json=/tmp/google_auth_credentials.json"
      - name: Build runtime image
        uses: docker/build-push-action@v6
        with:
          build-args: BUILDKIT_INLINE_CACHE=1
          cache-from: ${{ env.full_image_uri }}:latest
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: ${{ inputs.docker-push }}
          tags: |
            ${{ env.full_image_uri }}:latest
            ${{ env.full_image_uri }}:${{ github.sha }}
          secret-files: |
            "google_application_credentials.json=/tmp/google_auth_credentials.json"

  kubernetes_deploy:
    runs-on: ubuntu-22.04
    needs: [docker_build]
    if: |
      inputs.deployment-name != ''
      && inputs.cluster-name != ''
      && inputs.cluster-zone != ''
    steps:
      - uses: actions/checkout@v5
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GOOGLE_AUTHENTICATION_CREDENTIALS_JSON }}
      - uses: google-github-actions/get-gke-credentials@v3
        with:
          cluster_name: ${{ inputs.cluster-name }}
          location: ${{ inputs.cluster-zone }}
      - name: Update kubernetes image
        run: kubectl set image deployment/${{ inputs.deployment-name }} ${{ inputs.deployment-name }}-sha256-1=${{ env.full_image_uri }}:${{ github.sha }}
