name: Poetry build and publish
on:
  workflow_call:
    inputs:
      python-version:
        default: "3.11"
        required: false
        type: string
      repository:
        default: "zuos-python-repo"
        required: false
        type: string
      location:
        default: "europe-north1"
        required: false
        type: string
    secrets:
      GOOGLE_AUTHENTICATION_CREDENTIALS_JSON:
        description: "Google Cloud Platform service-agent JSON credentials for accessing our Artifact Repository and installing private packages."
        required: false

jobs:
  build-publish:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        env:
          GOOGLE_AUTHENTICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_AUTHENTICATION_CREDENTIALS_JSON }}
        if: ${{ env.GOOGLE_AUTHENTICATION_CREDENTIALS_JSON != '' }}
        with:
          credentials_json: ${{ secrets.GOOGLE_AUTHENTICATION_CREDENTIALS_JSON }}
      - name: Install dependencies
        uses: scene-connect/actions/python-package-manager/install-dependencies@v4
        with:
          package-manager: poetry
          python-version: ${{ inputs.python-version }}
      - name: Build
        run: poetry build --no-interaction
      # Only publish when pushing to main. But always attempt to buidl above first,
      # even if we won't publish next (i.e. PRs should build, to warn if the build fails)
      - name: Diff
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: technote-space/get-diff-action@v6
        id: diff
        with:
          PATTERNS: src/**/*
          FILES: poetry.lock
          FROM: github.event.before
      - name: Publish
        if: |
          github.event_name == 'push'
          && github.ref == 'refs/heads/main'
          && env.GIT_DIFF
        run: poetry publish --repository=${{ inputs.repository }} --no-interaction -vvv
