name: pre-commit autoupdate
on:
  workflow_call:
    inputs:
      package-manager:
        default: pipenv
        description: Package manager to use (pip, pipenv or poetry)
        required: false
        type: string
      python-version:
        default: "3.11"
        required: false
        type: string
      requirements-files:
        default: requirements.txt
        description: Space-separated list of requirements files if using pip
        required: false
        type: string
      system-dependencies:
        required: false
        type: string
    secrets:
      GOOGLE_AUTHENTICATION_CREDENTIALS_JSON:
        description: "Google Cloud Platform service-agent JSON credentials for accessing our Artifact Repository and installing private packages."
        required: false
      PRE_COMMIT_AUTO_UPDATE_ACCESS_TOKEN:
        description: "Github Personal Access Token with access to create a PR for the repo."
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      # Install our dependencies, so that we can run all our hooks to sanity-check
      # that they pass. The workflow fill fail if they don't pass, and we will have
      # to update the hooks manually.
      - uses: actions/checkout@v4
      - name: Authenticate with Google Cloud
        env:
          GOOGLE_AUTHENTICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_AUTHENTICATION_CREDENTIALS_JSON }}
        if: ${{ env.GOOGLE_AUTHENTICATION_CREDENTIALS_JSON != '' }}
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_AUTHENTICATION_CREDENTIALS_JSON }}
      - name: Install dependencies
        uses: scene-connect/actions/python-package-manager/install-dependencies@v4
        with:
          package-manager: ${{ inputs.package-manager }}
          python-version: ${{ inputs.python-version }}
          requirements-files: ${{ inputs.requirements-files }}
          system-dependencies: ${{ inputs.system-dependencies }}
      - name: Add symlink to local .venv
        # So that the pyright pre-commit hook runs with the dependencies in the venv.
        if: inputs.package-manager == 'pipenv'
        run: ln -s `pipenv --venv` .venv

      # Update pre-commit hooks and create a PR

      - name: pre-commit autoupdate
        uses: scene-connect/actions/python-package-manager/run-command@v4
        with:
          command: pre-commit autoupdate
          package-manager: ${{ inputs.package-manager }}
      - name: Check hooks still pass
        uses: scene-connect/actions/python-package-manager/run-command@v4
        with:
          command: pre-commit run --all-files
          package-manager: ${{ inputs.package-manager }}
      - uses: peter-evans/create-pull-request@v6
        id: pr
        with:
          branch: "pre-commit-autoupdate"
          title: "pre-commit autoupdate"
          commit-message: "pre-commit autoupdate"
          add-paths: .pre-commit-config.yaml
          token: ${{ secrets.PRE_COMMIT_AUTO_UPDATE_ACCESS_TOKEN }}
      - name: Enable PR automerge
        env:
          GH_TOKEN: ${{ secrets.PRE_COMMIT_AUTO_UPDATE_ACCESS_TOKEN }}
        run: gh pr merge --squash --auto "${{ steps.pr.outputs.pull-request-number }}"
