name: pre-commit autoupdate
on:
  schedule:
    - cron: "0 0 * * 0"  # midnight every sunday
  workflow_dispatch:

jobs:
  autoupdate:
    uses: scene-connect/actions/.github/workflows/pre-commit-autoupdate.yml@v2
    secrets:
      PRE_COMMIT_AUTO_UPDATE_ACCESS_TOKEN: ${{ secrets.PRE_COMMIT_AUTO_UPDATE_ACCESS_TOKEN }}
