name: Install pipenv dependencies
inputs:
  python-version:
    default: "3.11"
    required: false
    type: string
  requirements-files:
    default: requirements.txt
    description: Space-separated list of requirements files if using pip
    required: false
    type: string
  use-private-repo:
    default: false
    description: Use the ZUoS private GCloud Artifact Registry (required GCloud authentication)
    required: false
    type: boolean

runs:
  using: "composite"
  steps:
    - name: Ensure virtualenv is not created in the project
      run: rm -rf .venv
      shell: bash
    - uses: actions/setup-python@v4
      with:
        cache: "pipenv"
        python-version: "3.11"
    - name: Install pipenv
      run: pip install pipenv
      shell: bash
    - name: Prepare Google Artifact Registry keyring
      if: inputs.use-private-repo
      # Install dependencies for accessing our private packages repo (keyring for authenticating to GCP Artifact Registry).
      run: pipenv run init-private-repo
      shell: bash
    - name: Install pipenv dependencies
      run: pipenv install --dev --deploy
      shell: bash
