name: Install pipenv dependencies
inputs:
  python-version:
    default: "3.11"
    required: false
    type: string
  requirements-files:
    default: requirements.txt
    description: Space-separated list of requirements files if using pip
    required: false
    type: string
  system-dependencies:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - uses: scene-connect/actions/install-dependencies/system-dependencies@install-dependencies
      if: inputs.system-dependencies
      with:
        system-dependencies: ${{ inputs.system-dependencies }}
    - name: Ensure virtualenv is not created in the project
      run: rm -rf .venv
      shell: bash
    - uses: actions/setup-python@v4
      with:
        cache: "pipenv"
        python-version: "3.11"
    - name: Install pipenv
      run: pip install pipenv
      shell: bash
    - name: Prepare Google Artifact Registry keyring
      if: env.GOOGLE_APPLICATION_CREDENTIALS
      # Install build dependencies (keyring for authenticating to our GCP Artifact Registry python packages).
      run: pipenv run install-build-dependencies
      shell: bash
    - name: Install pipenv dependencies
      run: pipenv install --dev --deploy
      shell: bash
    - name: Activate virtualenv
      run: |
        . `pipenv --venv`/bin/activate
        echo PATH=$PATH >> $GITHUB_ENV
      shell: bash
    - name: DEBUG
      run: which python
      shell: bash
